services:
    _defaults:
        autowire: true

    Oveleon\ContaoMemberNotification\Controller\MemberNotificationController:
        arguments:
            - '@contao.framework'
        tags:
            - controller.service_arguments
